server:
  port: 8090
girl:
  cupSize: B


#这个就是把mysql配置完成了，  其他的什么都有默认最合适的配置 不用管， 除非有特别的想法， 就去加一下其他配置
spring:
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: xj663812
      url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&useSSL=false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    dialect: org.hibernate.dialect.MySQL5Dialect 新版本方言如下 不然报DDL错误
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql


  data:
    mongodb:
      primary:
        database: cardata
        port: 27017
        host:
      secondary:
          database: parse-app-dev
          username: xiajing
          authentication-database: parse-app-dev
          password: xj663812
          port: 11480
          host:



  redis:
    host: 192.168.1.9
    port: 6379
    password:

logging:
  config: classpath:log4j2.xml


