server:
  port: 8090
girl:
  cupSize: B

#这个就是把mysql配置完成了，  其他的什么都有默认最合适的配置 不用管， 除非有特别的想法， 就去加一下其他配置
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: xj663812
      url: jdbc:mysql://localhost:3306/cardata_collector?characterEncoding=utf-8&useSSL=false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    dialect: org.hibernate.dialect.MySQL5Dialect 新版本方言如下 不然报DDL错误
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql


  data:
    mongodb:
      primary:
        database: cardata
        port: 27017
        host: 172.16.249.134
      secondary:
          database: parse-app-dev
          username: xiajing
          authentication-database: parse-app-dev
          password: xj663812
          port: 11480
          host: ds011480-a0.ldb79.fleet.mlab.com





#      uri: mongodb://ds011480-a0.ldb79.fleet.mlab.com:11480
#      database: parse-app-dev
#      authentication-database: admin
#      host: 10.0.0.99
#      port: 11480
#      username: pump
#      password: !YCnf%t3&cyZ0<4R?C/Gm~



#      uri: mongodb://pump:!YCnf%t3%26cyZ0<4R%3FC/Gm~@ds011480-a0.ldb79.fleet.mlab.com:11480?ssl=true&replicaSet=rs-ds011480&readPreference=primaryPreferred
#      authentication-database: parsedb
#


#      uri: mongodb://54.172.20.250:11480
#      uri: mongodb://nonda:R^d[LFQ9H]K<Yy0q>@ds011480-a1.ldb79.fleet.mlab.com:11480,ds011480-a0.ldb79.fleet.mlab.com:11480/parse-app-dev?replicaSet=rs-ds011480&ssl=true

#      host: 54.172.20.250
#      port: 11480
# host: ds011480-a1.ldb79.fleet.mlab.com


